### ISSUE TITLE
Enhance validate method

### ISSUE THREAD

**Issue by peter279k** [selective-php/luhn#2]
I think we can enhance `validate` method. My approach is as follows:

Each of the numbers 79927398710, 79927398711, 79927398712, 79927398713, 79927398714, 79927398715, 79927398716, 79927398717, 79927398718, 79927398719 can be validated as follows.

- Double every second digit, from the rightmost: (1×2) = 2, (8×2) = 16, (3×2) = 6, (2×2) = 4, (9×2) = 18
- Sum all the individual digits (digits in parentheses are the products from Step 1): x (the check digit) + (2) + 7 + (1+6) + 9 + (6) + 7 + (4) + 9 + (1+8) + 7 = x + 67.
- If the sum is a multiple of 10, the account number is possibly valid. Note that 3 is the only valid digit that produces a sum (70) that is a multiple of 10.
    Thus these account numbers are all invalid except possibly 79927398713 which has the correct check digit.

That is, the return value statement in validate method should be as follows:

```php
......
return $number[strlen(number)-1] === (($sum % 10) * 10 - $sum);
......
```

or

```php
......
return substr($number, -1) === (($sum % 10) * 10 - $sum);
......
```

**Comment by odan** [comment]
Sounds good, but we should add unit tests first (for the current implementation) and then add the new enhanced validation check.

**Comment by odan** [comment]
I think we keep the current (working) concept.
