### ISSUE TITLE
The integer limitation for card number

### ISSUE THREAD

**Issue by peter279k** [selective-php/luhn#7]
As title, I use casting string to integer type to let card number be integer and do validation.

But the integer has the limitation.

My suggestions are as follows:

- Throw exception if number is greater than max integer  value.
- Using GMP extension instead.

@odan, what do you think?

**Comment by odan** [comment]
No, because in reality card numbers can be very long. I don't want to limit the max number to INT_MAX or use any extension for this. 

I think a numeric validation (with InvalidArgumentException) would be fine.

**Comment by peter279k** [comment]
How about resolving the long card numeric string?

**Comment by peter279k** [comment]
I also think the [GMP extension](https://www.php.net/manual/en/book.gmp.php) can help us to validate the real card number string.

**Comment by odan** [comment]
> How about resolving the long card numeric string?

The $number could be validated with a regex check like this.

```php
$number = '1234567890';

if (!preg_match('/^\d+$/', $number)) {
    throw new InvalidArgumentException(sprintf('An invalid numeric value was given: %s', $number));
}
```
